#! /bin/sh

echo Wait for http://elastic:9200/ to returns an HTTP 200
while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' elastic:9200)" != "200" ]]; do
    echo -n 'ElasticSearch not ready'
    sleep 10
done
echo ElasticSearch running and responsive

# Populate Kibana dashboard schema into ElasticSearch
metricbeat modules enable apache system
metricbeat setup

filebeat modules enable system
filebeat setup

#Use exec so that the kibana process replaces the shell
exec kibana -c /etc/kibana/kibana.yml